services:
  app:
    build:
      context: ..
      dockerfile: docker_compose/Dockerfile
    container_name: redirect_link_app
    volumes:
      - ../:/app
    working_dir: /app
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: redirect_link_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data_redirect_link_app:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres_data_redirect_link_app:
